### ISSUE TITLE
Node.js Services fail and stop handling rabbitmq messages

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1177]
**Describe the bug**
Sometimes the node.js services fail with an error and stop handling rabbitmq messages all together:

```
(node:37) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `content` of 'undefined' or 'null'.
    at readFromRabbitMQ (/app/services/logs2slack/build/readFromRabbitMQ.js:29:7)
    at Promise.all.channel.consume.msg (/app/services/logs2slack/build/index.js:25:48)
    at ConfirmChannel.BaseChannel.dispatchMessage (/app/node_modules/amqplib/lib/channel.js:478:12)
    at ConfirmChannel.BaseChannel.handleCancel (/app/node_modules/amqplib/lib/channel.js:491:15)
    at emitOne (events.js:116:13)
    at ConfirmChannel.emit (events.js:211:7)
    at ConfirmChannel.C.accept (/app/node_modules/amqplib/lib/channel.js:403:17)
    at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/app/node_modules/amqplib/lib/connection.js:478:48)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
(node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Usually it seems this happens when the rabbitmq is restarting

**Expected behavior**
service to not stop processing messages.
I think for now we could just catch the Exception and output some information about the message (maybe the whole body) and ack the message and with that continue processing messages

**Comment by tobybellwood** [comment]
I don't think we've seen this for a long time?
