### ISSUE TITLE
cronjob-logs-db-curator-curator seems to be broken

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1449]
**Describe the bug**
```

2019-12-02T23:01:14Z CRONJOB: /lagoon/cronjob.sh "/usr/bin/curator --config /curator/curator.yml /curator/actions.yml"
--
  | 2019-12-02T23:01:14Z CRONJOB: /usr/bin/curator --config /curator/curator.yml /curator/actions.yml
  | 2019-12-02 23:01:15,347 INFO      Preparing Action ID: 1, "index_settings"
  | Traceback (most recent call last):
  | File "/usr/bin/curator", line 14, in <module>
  | load_entry_point('elasticsearch-curator==5.7.6', 'console_scripts', 'curator')()
  | File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  | return self.main(*args, **kwargs)
  | File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
  | rv = self.invoke(ctx)
  | File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  | return callback(*args, **kwargs)
  | File "/usr/lib/python2.7/site-packages/curator/cli.py", line 218, in cli
  | run(config, action_file, dry_run)
  | File "/usr/lib/python2.7/site-packages/curator/cli.py", line 165, in run
  | client = get_client(**client_args)
  | File "/usr/lib/python2.7/site-packages/curator/utils.py", line 911, in get_client
  | 'Error: {0}'.format(e)
  | elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: AuthenticationException(401, u'Authentication finally failed')
```

**To Reproduce**
1. check the curator cronjobs
**Expected behavior**
Curator runs and curates the ES indexes

**Comment by dasrecht** [comment]
This seems to be mainly due to the fact that LOGSDB_ADMIN_PASSWORD isn't added to the cronjob - as we started to move cronjobs into job objects

**Comment by dasrecht** [comment]
I think this comes from the automatic switch between running cron jobs in a container or running it in a job object - for this i'd somehow make sure we run it in the container
