### ISSUE TITLE
Error on make lagoon-kickstart

### ISSUE THREAD

**Issue by stmh** [uselagoon/lagoon#272]
Hi, 

I am trying out lagoon on a small cloud server where OpenShift is already running.

1. I checked out the master branch of lagoon
2. i login into OpenShift via `oc login`
3. I run `make openshift-lagoon-setup` sucessfully
4. I adapted `local-dev/api-data/api-data.gql` as described in the documentation
5. I run `make lagoon-kickstart` 
6. now some docker container get built
7. It stops with an error message:

```
# make lagoon-kickstart
docker build --quiet --build-arg IMAGE_REPO=lagoon -t lagoon/local-api-data-watcher-pusher -f local-dev/api-data-watcher-pusher/Dockerfile local-dev/api-data-watcher-pusher
Sending build context to Docker daemon   5.12kB
Step 1/5 : FROM alpine:3.7
 ---> 3fd9065eaf02
Step 2/5 : RUN apk add --no-cache mysql-client tini openssl bash wget curl nodejs nodejs-npm     && npm -g install jwtgen
 ---> Running in 6408eff446a2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/25) Installing pkgconf (1.3.10-r0)
(2/25) Installing ncurses-terminfo-base (6.0_p20171125-r0)
(3/25) Installing ncurses-terminfo (6.0_p20171125-r0)
(4/25) Installing ncurses-libs (6.0_p20171125-r0)
(5/25) Installing readline (7.0.003-r0)
(6/25) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(7/25) Installing ca-certificates (20171114-r0)
(8/25) Installing libssh2 (1.8.0-r2)
(9/25) Installing libcurl (7.58.0-r1)
(10/25) Installing curl (7.58.0-r1)
(11/25) Installing mariadb-common (10.1.28-r1)
(12/25) Installing mariadb-client (10.1.28-r1)
(13/25) Installing mysql-client (10.1.28-r1)
(14/25) Installing nodejs-npm (8.9.3-r0)
(15/25) Installing c-ares (1.13.0-r0)
(16/25) Installing libcrypto1.0 (1.0.2n-r0)
(17/25) Installing libgcc (6.4.0-r5)
(18/25) Installing http-parser (2.7.1-r1)
(19/25) Installing libssl1.0 (1.0.2n-r0)
(20/25) Installing libstdc++ (6.4.0-r5)
(21/25) Installing libuv (1.17.0-r0)
(22/25) Installing nodejs (8.9.3-r0)
(23/25) Installing openssl (1.0.2n-r0)
(24/25) Installing tini (0.16.1-r0)
(25/25) Installing wget (1.19.2-r1)
Executing busybox-1.27.2-r7.trigger
Executing ca-certificates-20171114-r0.trigger
OK: 101 MiB in 36 packages
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:214:22)
    at /usr/lib/node_modules/npm/lib/npm.js:252:24
    at /usr/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:178:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:237:22)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
The command '/bin/sh -c apk add --no-cache mysql-client tini openssl bash wget curl nodejs nodejs-npm     && npm -g install jwtgen' returned a non-zero code: 7
make: *** [build/local-api-data-watcher-pusher] Fehler 7
``` 

I am using 
* CentOS Linux release 7.4.1708 (Core),  
* Docker version 17.12.0-ce, build c97c6d6
* 
    ```
    # oc version
    oc v3.7.1+ab0f056
    kubernetes v1.7.6+a08f5eeb62
    features: Basic-Auth GSSAPI Kerberos SPNEGO

    Server https://195.201.88.196:8443
    openshift v3.7.1+ab0f056
    kubernetes v1.7.6+a08f5eeb62
    ```

Any idea what is going wrong?

**Comment by Schnitzel** [comment]
@stmh 
thanks for trying it out! You definitely did everything correct, I will have a look in a couple of hours.

Michael

**Comment by stmh** [comment]
@Schnitzel the same docker image builds on my mac with minishift :-/

**Comment by Schnitzel** [comment]
@stmh 
yea, I can't reproduce the issue. Can you run `make clean` and try again?

also, you can with no problem run `make lagoon-kickstart` on your local mac and deploy into a remote openshift :)

**Comment by igayoso** [comment]
#466

**Comment by dasrecht** [comment]
Closing due to inactivity. Feel free to reopen if needed.
