### ISSUE TITLE
pygmy up is throwing the following error

### ISSUE THREAD

**Issue by justinlevi** [uselagoon/lagoon#311]
```
Error response from daemon: driver failed programming external connectivity on endpoint amazeeio-haproxy (5508c6d5eb7c34b39052c96b70a8925a9de348739cc26e83a32d19e802669eef): Error starting userland proxy: Bind for 0.0.0.0:443: unexpected error (Failure EADDRINUSE)
Error: failed to start containers: amazeeio-haproxy
/usr/local/lib/ruby/gems/2.3.0/gems/pygmy-0.9.8/lib/pygmy/docker_service.rb:13:in `start': Failed to run amazeeio-haproxy.  Command docker run -d -p 80:80 -p 443:443 --volume=/var/run/docker.sock:/tmp/docker.sock --restart=always --name=amazeeio-haproxy amazeeio/haproxy failed (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/pygmy-0.9.8/bin/pygmy:126:in `exec_up'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pygmy-0.9.8/bin/pygmy:33:in `up'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pygmy-0.9.8/bin/pygmy:300:in `<top (required)>'
	from /usr/local/bin/pygmy:22:in `load'
	from /usr/local/bin/pygmy:22:in `<main>'

```

Note, I had my own dnsmasq up and running based on a local apache install. Wondering if that's the issue here.

**Comment by dasrecht** [comment]
Hi @justinlevi 

It looks you have a service running on your local port `443`. As pygmy binds to port `80` and `443` you will need to stop services on your machine to start pygmy successfully.

/bastian

**Comment by justinlevi** [comment]
@dasrecht yah - just figured that out based on a conversation that was happening on the slack channel. thx

Is there any way to run a preflight check for these ports prior to building that command. The error message is decipherable but a bit cryptic if you've never worked with pygmy before.

**Comment by dasrecht** [comment]
We are working on something that would print a better error message than the one we currently see from docker.
