### ISSUE TITLE
logs2logs-db failure

### ISSUE THREAD

**Issue by JeffVeit** [uselagoon/lagoon#375]
make up and make lagoon-kickstart fail.

I think I managed to grab the relevant part of the make up logs, after where I've cut it, it goes into an endless cycle of uncaught exceptions. What is odd though is that I have had a successful lagoon-kickstart, so I'm guessing that time I won in a race.

`logs2logs-db_1                    | [2018-05-02T09:20:07,055][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash_system:xxxxxx@logs-db:9200/, :path=>"/"}
logs2logs-db_1                    | [2018-05-02T09:20:07,058][INFO ][logstash.licensechecker.licensereader] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash_system:xxxxxx@logs-db:9200/, :path=>"/"}
logs2logs-db_1                    | [2018-05-02T09:20:07,102][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://logstash_system:xxxxxx@logs-db:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash_system:xxxxxx@logs-db:9200/][Manticore::ResolutionFailure] logs-db"}
logs2logs-db_1                    | [2018-05-02T09:20:07,104][WARN ][logstash.licensechecker.licensereader] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://logstash_system:xxxxxx@logs-db:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash_system:xxxxxx@logs-db:9200/][Manticore::ResolutionFailure] logs-db"}
logs2logs-db_1                    | [2018-05-02T09:20:07,269][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://logs-db:9200/]}}
logs2logs-db_1                    | [2018-05-02T09:20:07,270][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logs-db:9200/, :path=>"/"}
logs2logs-db_1                    | [2018-05-02T09:20:07,276][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://logs-db:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logs-db:9200/][Manticore::ResolutionFailure] logs-db"}
logs2logs-db_1                    | [2018-05-02T09:20:07,278][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
logs2logs-db_1                    | [2018-05-02T09:20:07,281][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Template file '' could not be found!", :class=>"ArgumentError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/template_manager.rb:31:in `read_template_file'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/template_manager.rb:17:in `get_template'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/template_manager.rb:7:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:57:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:26:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:43:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:343:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:354:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:354:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:743:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:364:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:288:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:248:in `block in start'"]}
logs2logs-db_1                    | [2018-05-02T09:20:07,283][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://logs-db:9200"]}
logs2logs-db_1                    | [2018-05-02T09:20:07,297][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"service-logs", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1000, :thread=>"#<Thread:0x203a9c39 run>"}
logs2logs-db_1                    | [2018-05-02T09:20:07,607][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"service-logs"}
logs2logs-db_1                    | [2018-05-02T09:20:07,660][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logs-db:9200/, :path=>"/"}
logs2logs-db_1                    | [2018-05-02T09:20:07,663][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://logs-db:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logs-db:9200/][Manticore::ResolutionFailure] logs-db"}
logs2logs-db_1                    | [2018-05-02T09:20:07,743][INFO ][logstash.agent           ] Pipelines running {:count=>4, :pipelines=>[".monitoring-logstash", "lagoon-logs", "router-logs", "service-logs"]}
logs2logs-db_1                    | [2018-05-02T09:20:07,769][ERROR][logstash.inputs.metrics  ] Monitoring is not available: License information is currently unavailable. Please make sure you have added your production elasticsearch connection info in the xpack.monitoring.elasticsearch settings.
logs-db-ui_1                      | {"type":"log","@timestamp":"2018-05-02T09:20:07Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://logs-db:9200/"}
logs-db-ui_1                      | {"type":"log","@timestamp":"2018-05-02T09:20:07Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
logs2logs-db_1                    | [2018-05-02T09:20:08,274][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `<' for nil:NilClass>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:213:in `get_event_type'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:165:in `event_action_params'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:39:in `event_action_tuple'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:34:in `block in multi_receive'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.2-java/lib/logstash/outputs/elasticsearch/common.rb:34:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:50:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:487:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:486:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:438:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:393:in `block in start_workers'"]}
rabbitmq_1                        | 2018-05-02 09:20:08.775 [warning] <0.1358.0> closing AMQP connection <0.1358.0> (172.21.0.24:43328 -> 172.21.0.6:5672, vhost: '/', user: 'guest'):
rabbitmq_1                        | client unexpectedly closed TCP connection
lagoon_logs2logs-db_1 exited with code 1
webhooks2tasks_1                  | 2018-05-02T09:20:09.775Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:20:09 GMT+0000 (UTC), pid=50, uid=0, gid=0, cwd=/app/services/webhooks2tasks, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/webhooks2tasks/src/index.js], rss=55701504, heapTotal=26075136, heapUsed=19509800, external=94840, loadavg=[3.4521484375, 1.48095703125, 1.06005859375], uptime=83820, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftbuilddeploy_1            | 2018-05-02T09:20:09.776Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:20:09 GMT+0000 (UTC), pid=44, uid=0, gid=0, cwd=/app/services/openshiftbuilddeploy, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/openshiftbuilddeploy/src/index.js], rss=65261568, heapTotal=23007232, heapUsed=20361440, external=37444, loadavg=[3.4521484375, 1.48095703125, 1.06005859375], uptime=83820, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftbuilddeploymonitor_1     | 2018-05-02T09:20:09.776Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:20:09 GMT+0000 (UTC), pid=50, uid=0, gid=0, cwd=/app/services/openshiftbuilddeploymonitor, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/openshiftbuilddeploymonitor/src/index.js], rss=80068608, heapTotal=35065856, heapUsed=28445168, external=78436, loadavg=[3.4521484375, 1.48095703125, 1.06005859375], uptime=83820, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
`

Here's a clip of a lagoon-kickstart:
` make lagoon-kickstart
IMAGE_REPO=lagoon CI_USE_OPENSHIFT_REGISTRY=false docker-compose -p lagoon up -d rabbitmq openshiftremove openshiftbuilddeploy openshiftbuilddeploymonitor logs2slack api ssh auth-server local-git local-api-data-watcher-pusher local-es-kibana-watcher-pusher tests rest2tasks
lagoon_rest2tasks_1 is up-to-date
lagoon_logs-db-ui_1 is up-to-date
lagoon_api-db_1 is up-to-date
lagoon_openshiftremove_1 is up-to-date
Starting lagoon_tests_1 ... 
lagoon_logs2slack_1 is up-to-date
lagoon_openshiftbuilddeploymonitor_1 is up-to-date
Recreating lagoon_openshiftbuilddeploy_1 ... 
lagoon_local-git_1 is up-to-date
lagoon_auth-server_1 is up-to-date
Starting lagoon_logs-db_1                ... 
lagoon_rabbitmq_1 is up-to-date
Starting lagoon_tests_1                  ... done
lagoon_api_1 is up-to-date
Recreating lagoon_openshiftbuilddeploy_1 ... done
lagoon_local-es-kibana-watcher-pusher_1 is up-to-date
sleep 30
curl -X POST http://localhost:5555/deploy -H 'content-type: application/json' -d '{ "projectName": "lagoon", "branchName": "master" }'
{"ok":"true","message":"lagoon-tasks: Successfully created task 'builddeploy-openshift': {\"projectName\":\"lagoon\",\"branchName\":\"master\",\"type\":\"branch\"}"}make logs
make[1]: Entering directory '/home/jeff/projects/lagoon-learning/lagoon'
IMAGE_REPO=lagoon docker-compose -p lagoon logs --tail=10 -f 
Attaching to lagoon_openshiftbuilddeploy_1, lagoon_local-es-kibana-watcher-pusher_1, lagoon_cli_1, lagoon_ssh_1, lagoon_api_1, lagoon_local-api-data-watcher-pusher_1, lagoon_rabbitmq_1, lagoon_openshiftremove_1, lagoon_logs-db_1, lagoon_auth-server_1, lagoon_webhook-handler_1, lagoon_openshiftbuilddeploymonitor_1, lagoon_local-git_1, lagoon_remotedev_1, lagoon_drush-alias_1, lagoon_logs2logs-db_1, lagoon_hacky-rest2tasks-ui_1, lagoon_logs2slack_1, lagoon_rest2tasks_1, lagoon_webhooks2tasks_1, lagoon_api-db_1, lagoon_auto-idler_1, lagoon_logs-db-ui_1, lagoon_tests_1
openshiftbuilddeploy_1            |     at emitNone (events.js:111:20)
openshiftbuilddeploy_1            |     at IncomingMessage.emit (events.js:208:7)
openshiftbuilddeploy_1            |     at endReadableNT (_stream_readable.js:1064:12)
openshiftbuilddeploy_1            |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
openshiftbuilddeploy_1            |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
openshiftbuilddeploy_1            | 2018-05-02T09:25:04.444Z - warn: lagoon-logs: Send to lagoon-logs: *[lagoon]* `master` ERROR:
openshiftbuilddeploy_1            | ```
openshiftbuilddeploy_1            | Error
openshiftbuilddeploy_1            | ```
openshiftbuilddeploy_1            | Retrying deployment in 10 secs
100    73    0    61  100    12   6777   1333 --:--:-- --:--:-- --:--:--  8111
local-es-kibana-watcher-pusher_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
local-es-kibana-watcher-pusher_1  |                                  Dload  Upload   Total   Spent    Left  Speed
100    73    0    61  100    12   7625   1500 --:--:-- --:--:-- --:--:--  9125
local-es-kibana-watcher-pusher_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
local-es-kibana-watcher-pusher_1  |                                  Dload  Upload   Total   Spent    Left  Speed
100    73    0    61  100    12   5083   1000 --:--:-- --:--:-- --:--:--  6636
local-es-kibana-watcher-pusher_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
local-es-kibana-watcher-pusher_1  |                                  Dload  Upload   Total   Spent    Left  Speed
100    73    0    61  100    12   5545   1090 --:--:-- --:--:-- --:--:--  6636
cli_1                             | sleep: invalid number 'infinity'
cli_1                             | Agent pid 14
cli_1                             | Identity added: /home/.ssh/id_rsa (/home/.ssh/id_rsa)
cli_1                             | sleep: invalid number 'infinity'
cli_1                             | Agent pid 14
cli_1                             | Identity added: /home/.ssh/id_rsa (/home/.ssh/id_rsa)
cli_1                             | sleep: invalid number 'infinity'
cli_1                             | Agent pid 14
cli_1                             | Identity added: /home/.ssh/id_rsa (/home/.ssh/id_rsa)
cli_1                             | sleep: invalid number 'infinity'
lagoon_cli_1 exited with code 0
api_1                             | 
api_1                             | debug: No Bearer Token
api_1                             | info: ::ffff:172.21.0.1 - - [02/May/2018:09:05:44 +0000] "GET /favicon.ico HTTP/1.1" 401 63 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/65.0.3325.181 Chrome/65.0.3325.181 Safari/537.36"
api_1                             | 
api_1                             | info: ::ffff:172.21.0.4 - - [02/May/2018:09:25:04 +0000] "POST /graphql HTTP/1.1" 200 159 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
api_1                             | 
api_1                             | info: ::ffff:172.21.0.5 - - [02/May/2018:09:25:04 +0000] "POST /graphql HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
api_1                             | 
api_1                             | info: ::ffff:172.21.0.10 - - [02/May/2018:09:25:04 +0000] "POST /graphql HTTP/1.1" 200 230 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
api_1                             | 
ssh_1                             | Server listening on :: port 2020.
ssh_1                             | Received signal 15; terminating.
ssh_1                             | Server listening on 0.0.0.0 port 2020.
ssh_1                             | Server listening on :: port 2020.
ssh_1                             | Received signal 15; terminating.
ssh_1                             | Server listening on 0.0.0.0 port 2020.
ssh_1                             | Server listening on :: port 2020.
ssh_1                             | Received signal 15; terminating.
ssh_1                             | Server listening on 0.0.0.0 port 2020.
ssh_1                             | Server listening on :: port 2020.
openshiftremove_1                 | 2018-05-02T09:22:04.975Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:22:04 GMT+0000 (UTC), pid=50, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/openshiftremove/src/index.js], rss=62005248, heapTotal=32968704, heapUsed=24860192, external=78308, loadavg=[1.48193359375, 1.31494140625, 1.041015625], uptime=83935, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-05-02T09:22:05.977Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:22:05 GMT+0000 (UTC), pid=50, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/openshiftremove/src/index.js], rss=62005248, heapTotal=32968704, heapUsed=24903880, external=78308, loadavg=[1.48193359375, 1.31494140625, 1.041015625], uptime=83936, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-05-02T09:22:06.979Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:22:06 GMT+0000 (UTC), pid=50, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/openshiftremove/src/index.js], rss=62005248, heapTotal=32968704, heapUsed=24951056, external=78324, loadavg=[1.5234375, 1.32666015625, 1.04638671875], uptime=83937, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-05-02T09:22:07.981Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:22:07 GMT+0000 (UTC), pid=50, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/openshiftremove/src/index.js], rss=62005248, heapTotal=32968704, heapUsed=24995000, external=78324, loadavg=[1.5234375, 1.32666015625, 1.04638671875], uptime=83938, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-05-02T09:22:08.982Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:22:08 GMT+0000 (UTC), pid=50, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/openshiftremove/src/index.js], rss=62275584, heapTotal=32968704, heapUsed=25038744, external=78324, loadavg=[1.5234375, 1.32666015625, 1.04638671875], uptime=83939, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-05-02T09:24:37.944Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed May 02 2018 09:24:37 GMT+0000 (UTC), pid=50, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.1, argv=[node, /app/services/openshiftremove/src/index.js], rss=62545920, heapTotal=32968704, heapUsed=25404952, external=78804, loadavg=[2.7001953125, 2.123046875, 1.40869140625], uptime=84088, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1           `

**Comment by dasrecht** [comment]
Closing due to inactivity. Feel free to reopen if needed.
