### ISSUE TITLE
solr pods do not shut down properly

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#537]
Shutdown of solr images is not handled well during deployment, leading to files in the persistent storage which appear to the new pod that they are in use. Initial investigation leads this to look like the solr process is not getting the TERM signal.

**Comment by dasrecht** [comment]
Solr starts with following error when we hit that issue:

```
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [drupal]
  | at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  | at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  | at org.apache.solr.core.CoreContainer.lambda$load$6(CoreContainer.java:594)
  | at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.apache.solr.common.SolrException: Unable to create core [drupal]
  | at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:966)
  | at org.apache.solr.core.CoreContainer.lambda$load$5(CoreContainer.java:565)
  | at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
  | ... 5 more
  | Caused by: org.apache.solr.common.SolrException: Index dir '/opt/solr/server/solr/mycores/drupal/data/index/' of core 'drupal' is already locked. The most likely cause is another Solr server (or another solr core in this server) also configured to use this directory; other possible causes may be specific to lockType: native
  | at org.apache.solr.core.SolrCore.<init>(SolrCore.java:977)
  | at org.apache.solr.core.SolrCore.<init>(SolrCore.java:830)
  | at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:950)
  | ... 7 more
  | Caused by: org.apache.lucene.store.LockObtainFailedException: Index dir '/opt/solr/server/solr/mycores/drupal/data/index/' of core 'drupal' is already locked. The most likely cause is another Solr server (or another solr core in this server) also configured to use this directory; other possible causes may be specific to lockType: native
  | at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:712)
  | at org.apache.solr.core.SolrCore.<init>(SolrCore.java:923)
  | ... 9 more
  | 2018-08-08 03:26:53.211 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be created
  | java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [event]
  | at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  | at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  | at org.apache.solr.core.CoreContainer.lambda$load$6(CoreContainer.java:594)
  | at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.apache.solr.common.SolrException: Unable to create core [event]
  | at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:966)
  | at org.apache.solr.core.CoreContainer.lambda$load$5(CoreContainer.java:565)
  | at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
  | ... 5 more
 
````

**Comment by dasrecht** [comment]
- https://wiki.apache.org/lucene-java/AvailableLockFactories
- https://lucene.apache.org/solr/guide/6_6/indexconfig-in-solrconfig.html

**Comment by Schnitzel** [comment]
I would vote to use `NoLockFactory` as Docker can make sure that we are not running the same pod twice
