### ISSUE TITLE
Infinite loop when running make lagoon-kickstart - Issue with openshiftremove service with dns.js

### ISSUE THREAD

**Issue by amjad1233** [uselagoon/lagoon#573]
**Describe the bug**
After following steps in lagoon documentation
https://github.com/amazeeio/lagoon/blob/master/docs/administering_lagoon/install.md

When I make lagoon-kickstart the system gets stuck on infinite loop as per Aditional context area.

**To Reproduce**
1. `make build`
2. `make lagoon-kickstart`
3. Build all required Lagoon service Images (this can take a while)
4. Start all required Lagoon services
5. You see `sleep 30`
6. It starts infinite loop

**Expected behavior**
Should Trigger a deployment of the lagoon sitegroup that you edited further, which will cause your local lagoon to connect to the defined OpenShift and trigger a new deployment

** Versions **
Docker - 18
Node - 10
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

**Additional context**
```openshiftremove_1                 | 2018-08-15T06:09:10.224Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:10 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftremove/src/index.js], rss=37486592, heapTotal=24580096, heapUsed=20237536, external=57828, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7053, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
logs2slack_1                      | 2018-08-15T06:09:10.769Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:10 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/logs2slack, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/logs2slack/src/index.js], rss=36306944, heapTotal=22941696, heapUsed=19524440, external=83208, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7054, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftbuilddeploymonitor_1     | 2018-08-15T06:09:10.790Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:10 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftbuilddeploymonitor, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftbuilddeploymonitor/src/index.js], rss=53018624, heapTotal=36638720, heapUsed=25550224, external=113483, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7054, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftbuilddeploy_1            | 2018-08-15T06:09:11.031Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:11 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftbuilddeploy, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftbuilddeploy/src/index.js], rss=39997440, heapTotal=25104384, heapUsed=20766168, external=67301, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7054, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
rest2tasks_1                      | 2018-08-15T06:09:11.113Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:11 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/rest2tasks, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/rest2tasks/src/index.js], rss=34455552, heapTotal=21356544, heapUsed=17817704, external=65992, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7054, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
logs2rocketchat_1                 | 2018-08-15T06:09:11.220Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:11 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/logs2rocketchat, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/logs2rocketchat/src/index.js], rss=33325056, heapTotal=18210816, heapUsed=15121464, external=93009, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7054, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-08-15T06:09:11.227Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:11 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftremove/src/index.js], rss=37486592, heapTotal=24580096, heapUsed=20282512, external=57828, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7054, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
logs-db-ui_1                      | {"type":"log","@timestamp":"2018-08-15T06:09:11Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://logs-db:9200/"}
logs-db-ui_1                      | {"type":"log","@timestamp":"2018-08-15T06:09:11Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
logs2slack_1                      | 2018-08-15T06:09:11.772Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:11 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/logs2slack, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/logs2slack/src/index.js], rss=36306944, heapTotal=22941696, heapUsed=19568864, external=83208, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7055, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftbuilddeploymonitor_1     | 2018-08-15T06:09:11.796Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:11 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftbuilddeploymonitor, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftbuilddeploymonitor/src/index.js], rss=53018624, heapTotal=36638720, heapUsed=25594088, external=113483, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7055, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftbuilddeploy_1            | 2018-08-15T06:09:12.034Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:12 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftbuilddeploy, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftbuilddeploy/src/index.js], rss=39997440, heapTotal=25104384, heapUsed=20811256, external=67301, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7055, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
rest2tasks_1                      | 2018-08-15T06:09:12.115Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:12 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/rest2tasks, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/rest2tasks/src/index.js], rss=34455552, heapTotal=21356544, heapUsed=17862536, external=65992, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7055, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
logs2rocketchat_1                 | 2018-08-15T06:09:12.224Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:12 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/logs2rocketchat, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/logs2rocketchat/src/index.js], rss=33325056, heapTotal=18210816, heapUsed=15165872, external=93009, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7055, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-08-15T06:09:12.234Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Wed Aug 15 2018 06:09:12 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftremove/src/index.js], rss=37486592, heapTotal=24580096, heapUsed=20327680, external=57828, loadavg=[0.41259765625, 0.78369140625, 0.93115234375], uptime=7055, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
^CERROR: Aborting.
make[1]: *** [logs] Error 1
make: *** [lagoon-kickstart] Interrupt

[root@lagoon-2 lagoon]# ^C
```

**Comment by amjad-wp** [comment]
Some more info logs:
```
make lagoon-kickstart
IMAGE_REPO=lagoon CI_USE_OPENSHIFT_REGISTRY=false docker-compose -p lagoon up -d rabbitmq openshiftremove openshiftbuilddeploy openshiftbuilddeploymonitor logs2slack logs2rocketchat api ssh auth-server local-git local-api-data-watcher-pusher local-es-kibana-watcher-pusher tests rest2tasks
Creating network "lagoon_default" with the default driver
Creating lagoon_openshiftbuilddeploy_1        ... done
Creating lagoon_tests_1                       ... done
Creating lagoon_logs-db-ui_1                  ... done
Creating lagoon_api-db_1                      ... done
Creating lagoon_auth-server_1                    ... done
Creating lagoon_logs2rocketchat_1             ... done
Creating lagoon_logs-db_1                       ... done
Creating lagoon_openshiftremove_1             ... done
Creating lagoon_openshiftbuilddeploymonitor_1   ... done
Creating lagoon_rabbitmq_1                       ... done
Creating lagoon_rest2tasks_1                     ... done
Creating lagoon_logs2slack_1                     ... done
Creating lagoon_local-git_1                      ... done
Creating lagoon_local-api-data-watcher-pusher_1  ... done
Creating lagoon_local-es-kibana-watcher-pusher_1 ... done
Creating lagoon_api_1                            ... done
Creating lagoon_ssh_1                            ... done
sleep 30
curl -X POST http://localhost:5555/deploy -H 'content-type: application/json' -d '{ "projectName": "lagoon", "branchName": "master" }'
{"ok":"true","message":"lagoon-tasks: Successfully created task 'builddeploy-openshift': {\"projectName\":\"lagoon\",\"branchName\":\"master\",\"type\":\"branch\"}"}make logs
make[1]: Entering directory `/root/lagoon'
IMAGE_REPO=lagoon docker-compose -p lagoon logs --tail=10 -f 
Attaching to lagoon_ssh_1, lagoon_api_1, lagoon_local-es-kibana-watcher-pusher_1, lagoon_local-api-data-watcher-pusher_1, lagoon_local-git_1, lagoon_logs2slack_1, lagoon_rabbitmq_1, lagoon_logs-db_1, lagoon_openshiftremove_1, lagoon_openshiftbuilddeploymonitor_1, lagoon_rest2tasks_1, lagoon_logs2rocketchat_1, lagoon_auth-server_1, lagoon_api-db_1, lagoon_logs-db-ui_1, lagoon_tests_1, lagoon_openshiftbuilddeploy_1
ssh_1                             | /etc/ssh/sshd_config line 37: Deprecated option UsePrivilegeSeparation
ssh_1                             | Server listening on 0.0.0.0 port 2020.
ssh_1                             | Server listening on :: port 2020.
api_1                             | info: ::ffff:172.18.0.8 - - [16/Aug/2018:01:13:53 +0000] "POST /graphql HTTP/1.1" 200 159 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
api_1                             | 
api_1                             | info: ::ffff:172.18.0.7 - - [16/Aug/2018:01:13:53 +0000] "POST /graphql HTTP/1.1" 200 259 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
api_1                             | 
api_1                             | info: ::ffff:172.18.0.3 - - [16/Aug/2018:01:13:53 +0000] "POST /graphql HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
api_1                             | 
api_1                             | info: ::ffff:172.18.0.10 - - [16/Aug/2018:01:13:53 +0000] "POST /graphql HTTP/1.1" 200 61 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
api_1                             | 
api_1                             | info: ::ffff:172.18.0.3 - - [16/Aug/2018:01:13:53 +0000] "POST /graphql HTTP/1.1" 200 265 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
api_1                             | 
local-api-data-watcher-pusher_1   |     "KickstartOpenshift": {
local-api-data-watcher-pusher_1   |       "id": 3
local-api-data-watcher-pusher_1   |     },
local-api-data-watcher-pusher_1   |     "KickstartProject": {
local-api-data-watcher-pusher_1   |       "id": 13
local-api-data-watcher-pusher_1   |     },
local-api-data-watcher-pusher_1   |     "KickstartRocketChatNotification": {
local-api-data-watcher-pusher_1   |       "id": 13
local-api-data-watcher-pusher_1   |     }
local-api-data-watcher-pusher_1   |   }
local-es-kibana-watcher-pusher_1  | tar: removing leading '/' from member names
local-es-kibana-watcher-pusher_1  | ******* found changes in /lagoon/kibana-init.sh, updating
local-es-kibana-watcher-pusher_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
local-es-kibana-watcher-pusher_1  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to logs-db-ui port 5601: Connection refused
local-es-kibana-watcher-pusher_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
local-es-kibana-watcher-pusher_1  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to logs-db-ui port 5601: Connection refused
local-git_1                       | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
local-git_1                       | *** Running /etc/my_init.d/authorized-keys.sh...
local-git_1                       | *** Running /etc/rc.local...
local-git_1                       | *** Booting runit daemon...
local-git_1                       | *** Runit started as PID 9
local-git_1                       | tail: unrecognized file system type 0x794c7630 for ‘/var/log/syslog’. please report this to bug-coreutils@gnu.org. reverting to polling
rabbitmq_1                        | 2018-08-16 01:13:46.927 [info] <0.750.0> accepting AMQP connection <0.750.0> (172.18.0.10:58754 -> 172.18.0.14:5672)
rabbitmq_1                        | 2018-08-16 01:13:46.972 [info] <0.750.0> connection <0.750.0> (172.18.0.10:58754 -> 172.18.0.14:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1                        | 2018-08-16 01:13:47.135 [info] <0.767.0> accepting AMQP connection <0.767.0> (172.18.0.8:36470 -> 172.18.0.14:5672)
rabbitmq_1                        | 2018-08-16 01:13:47.139 [info] <0.770.0> accepting AMQP connection <0.770.0> (172.18.0.8:36472 -> 172.18.0.14:5672)
rabbitmq_1                        | 2018-08-16 01:13:47.180 [info] <0.767.0> connection <0.767.0> (172.18.0.8:36470 -> 172.18.0.14:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1                        | 2018-08-16 01:13:47.182 [info] <0.770.0> connection <0.770.0> (172.18.0.8:36472 -> 172.18.0.14:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1                        | 2018-08-16 01:13:47.272 [info] <0.793.0> accepting AMQP connection <0.793.0> (172.18.0.9:54164 -> 172.18.0.14:5672)
rabbitmq_1                        | 2018-08-16 01:13:47.279 [info] <0.799.0> accepting AMQP connection <0.799.0> (172.18.0.9:54166 -> 172.18.0.14:5672)
rabbitmq_1                        | 2018-08-16 01:13:47.317 [info] <0.793.0> connection <0.793.0> (172.18.0.9:54164 -> 172.18.0.14:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1                        | 2018-08-16 01:13:47.323 [info] <0.799.0> connection <0.799.0> (172.18.0.9:54166 -> 172.18.0.14:5672): user 'guest' authenticated and granted access to vhost '/'
openshiftremove_1                 | 2018-08-16T01:13:45.936Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Thu Aug 16 2018 01:13:45 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftremove/src/index.js], rss=52121600, heapTotal=38735872, heapUsed=21540208, external=558611, loadavg=[4.74267578125, 1.302734375, 0.92626953125], uptime=63491, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-08-16T01:13:46.745Z - verbose: lagoon-logs: Connected to amqp://guest:guest@rabbitmq action=connected, url=amqp://guest:guest@rabbitmq
openshiftremove_1                 | 2018-08-16T01:13:46.750Z - verbose: lagoon-tasks: Connected to amqp://guest:guest@rabbitmq action=connected, url=amqp://guest:guest@rabbitmq
openshiftremove_1                 | 2018-08-16T01:13:46.941Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Thu Aug 16 2018 01:13:46 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftremove/src/index.js], rss=52080640, heapTotal=38735872, heapUsed=22117048, external=561376, loadavg=[4.74267578125, 1.302734375, 0.92626953125], uptime=63492, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-08-16T01:13:47.943Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Thu Aug 16 2018 01:13:47 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftremove/src/index.js], rss=52064256, heapTotal=38735872, heapUsed=22162704, external=561376, loadavg=[4.68310546875, 1.34765625, 0.94287109375], uptime=63493, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-08-16T01:13:48.957Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Thu Aug 16 2018 01:13:48 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftremove/src/index.js], rss=52064256, heapTotal=38735872, heapUsed=22208408, external=561376, loadavg=[4.68310546875, 1.34765625, 0.94287109375], uptime=63494, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
openshiftremove_1                 | 2018-08-16T01:13:49.961Z - error: uncaughtException: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777 date=Thu Aug 16 2018 01:13:49 GMT+0000 (UTC), pid=47, uid=0, gid=0, cwd=/app/services/openshiftremove, execPath=/usr/local/bin/node, version=v8.11.3, argv=[node, /app/services/openshiftremove/src/index.js], rss=52064256, heapTotal=38735872, heapUsed=22255472, external=561376, loadavg=[4.68310546875, 1.34765625, 0.94287109375], uptime=63495, trace=[column=10, file=dns.js, function=errnoException, line=50, method=null, native=false, column=26, file=dns.js, function=GetAddrInfoReqWrap.onlookup [as oncomplete], line=92, method=onlookup [as oncomplete], native=false], stack=[Error: getaddrinfo ENOTFOUND logs2logs-db logs2logs-db:28777,     at errnoException (dns.js:50:10),     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)]
```

**Comment by blakemorgan** [comment]
I am having this same issue.

**Comment by amjad-wp** [comment]
@Schnitzel I will give it a go. Yope I have done `make lagoon-kickstart` several times. But it was the same results were coming up. Is there anyway we can take out the whole `log2logs-db` module ? Just curios.

Thanks.

**Comment by blakemorgan** [comment]
I tried `make lagoon-kickstart` multiple times as well, but have no luck. When I do `make up` and then `make lagoon-kickstart` I get stuck in an infinite loop while it's looking for elasticsearch.

**Comment by tobybellwood** [comment]
make lagoon-kickstart is deprecated in Lagoon 2
